<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

__Exercise 1 (Total recall) ☻__:

Purely from memory, write short descriptions of the following terms:
| Term       | Brief Description |
|------------|-------------------|
| Subsetting |Selecting a subset of the data in an iterable (Any sequence that can be iterated in a for loop (i.e. list-like objects: lists, arrays, tuples, dictionaries etc.)                   |
| Indexing   |Calling out _single element_ from a list/array/dictionary based on the data indices                   |
| Slicing    |Calling out data from a list/array from a specified section (i.e. data from a range of indices)                  |
| Masking    |Calling out data from an _numpy array_ that fulfils (`True`) a given condition                    |

__Exercise 2 (Show me the ‘odd’ letters) ☻__
```python
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
```
__Task:__ Use masking to subset the letters that correspond to the odd numbers. I.e., get the result `[A, C, E, G, I]`.

This is a slightly tricky problem because arrays are fussy about type. So, let me give you a recipe to solve this problem.

1. Subset all the first elements.
    - You should get `array(['1', '3', '2', ..., '10', '9'])`
1. Convert this to integers using `astype(int)`
    - You must look up how `astype()` works.
1. Use `%` to get the remainder for division by `2`.
    - You should get `array([1, 1, 0, ..., 0, 1])`.
1. Use the previous result to create a mask that checks if the remainder is zero or not
    - You should get array([True, True, False, ..., False, True])`.
    - Now you have identified the locations of the odd numbers.
1. Use the mask and extract the corresponding second elements.

In [3]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [5]:
np_array_2d [:, 0]

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [6]:
np_array_1d = np_array_2d [:, 0] 

In [8]:
np_array_1d_int = np_array_1d.astype(int)

In [21]:
np_array_1d_int

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [22]:
np_array_1d_int % 2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [29]:
np_array_1d_int % 2 == 1
#And now we've identified the odd number location

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [23]:
#Creating the mask
mask_for_odd = np_array_1d_int % 2 == 1

In [30]:
#Indexing the 2nd elements of the masked data
np_array_2d [mask_for_odd, 1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')